version: "3.9"
services:
  backend:
    build: backend
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0", "app:app"]
    volumes:
      - ./src/backend:/backend
    ports:
      - 8000:8000
    env_file:
      - backend/.env
      - frontend/.env

  frontend:
    build: frontend
    command: [ "npm", "start" ]
    volumes:
      - ./src/frontend:/frontend
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - backend

