export const DEFAULT = 'DEFAULT' // THIS IS FOR SETUP PURPOSES, DELETE WHENEVER

export const FETCH_STANDINGS_REQUEST = 'FETCH_STANDINGS_REQUEST';
export const FETCH_STANDINGS_SUCCESS = 'FETCH_STANDINGS_SUCCESS';
export const FETCH_STANDINGS_FAILURE = 'FETCH_STANDINGS_FAILURE';

export const FETCH_PERFORMANCES_REQUEST = 'FETCH_PERFORMANCES_REQUEST';
export const FETCH_PERFORMANCES_SUCCESS = 'FETCH_PERFORMANCES_SUCCESS';
export const FETCH_PERFORMANCES_FAILURE = 'FETCH_PERFORMANCES_FAILURE';
